version: '3'
services:
  proxy:
    container_name: proxy
    build:
      dockerfile: docker/prod/Dockerfile-proxy
      context: .
    ports:
      - 8000:80
    links:
      - php
  php:
    container_name: php
    build:
      dockerfile: ./docker/dev/Dockerfile
      context: .
    expose:
      - 9000
    volumes:
      - ./:/src:delegated
    links:
      - redis
  redis:
    container_name: redis
    image: redis
    volumes:
      - redis-data:/data:cached
    ports:
      - "6379:6379"
    network_mode: bridge
#  pg:
#    image: postgres:alpine
#    ports:
#      - '5433:5432'
#    container_name: pg
#    restart: always
#    volumes:
#      - pg-data-sellect:/var/lib/postgresql/data
#    environment:
#      POSTGRES_USER: pguser
#      POSTGRES_PASSWORD: pgpassword
#    network_mode: bridge
volumes:
  #  pg-data-sellect:
  redis-data:
